-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--          local scaleFactor = 1.0
--          local physicsData = (require "shapedefs").physicsData(scaleFactor)
--          local shape = display.newImage("objectname.png")
--          physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
    local physics = { data =
    { 
        
        ["seg1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -793, 0  ,  -791, 44  ,  -799, 12  ,  -800, 0  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -692, 402  ,  -688, 392  ,  -686, 395  ,  -685, 398  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -791, 44  ,  -786, 99  ,  -797, 60  ,  -799, 44  ,  -799, 12  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -686, 395  ,  -688, 392  ,  -686, 394  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -692, 402  ,  -734, 316  ,  -743, 294  ,  -688, 392  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -786, 99  ,  -782, 126  ,  -792, 108  ,  -795, 84  ,  -797, 60  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -775, 163  ,  -775, 204  ,  -792, 108  ,  -782, 126  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -770, 186  ,  -775, 204  ,  -775, 163  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -743, 294  ,  -775, 204  ,  -770, 186  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -730, 308  ,  -743, 294  ,  -741, 280  ,  -732, 302  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -699, 372  ,  -707, 357  ,  -704, 362  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -743, 294  ,  -707, 357  ,  -699, 372  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -743, 294  ,  -715, 341  ,  -707, 357  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -743, 294  ,  -726, 317  ,  -715, 341  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -743, 294  ,  -730, 308  ,  -726, 317  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -743, 294  ,  -748, 261  ,  -741, 280  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -743, 294  ,  -755, 240  ,  -748, 261  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -743, 294  ,  -761, 220  ,  -755, 240  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce=1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -743, 294  ,  -763, 213  ,  -761, 220  }
                    }
                    
                    
                    
        },

        ["tempmo"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1, 150  ,  -24, 138  ,  1, 140  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15, -140  ,  -23, -142  ,  1, -143  ,  1, -140  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -40, -135  ,  -55, -133  ,  -23, -142  ,  -15, -140  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -54, -130  ,  -55, -133  ,  -40, -135  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -72, -121  ,  -83, -124  ,  -55, -133  ,  -54, -130  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -89, -109  ,  -83, -124  ,  -72, -121  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -108, -90  ,  -144, -79  ,  -83, -124  ,  -89, -109  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -112, -85  ,  -144, -79  ,  -108, -90  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -126, -62  ,  -144, -79  ,  -112, -85  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -130, -53  ,  -144, -79  ,  -126, -62  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -138, -25  ,  -144, -79  ,  -130, -53  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -138, -25  ,  -140, 5  ,  -150, 30  ,  -144, -79  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -136, 34  ,  -150, 30  ,  -140, 5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -128, 57  ,  -118, 117  ,  -150, 30  ,  -136, 34  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -119, 74  ,  -118, 117  ,  -128, 57  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -113, 83  ,  -118, 117  ,  -119, 74  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -93, 105  ,  -118, 117  ,  -113, 83  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -83, 113  ,  -118, 117  ,  -93, 105  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -71, 121  ,  -118, 117  ,  -83, 113  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -55, 129  ,  -118, 117  ,  -71, 121  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -55, 129  ,  1, 150  ,  -118, 117  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1, 150  ,  -38, 135  ,  -24, 138  }
                    }
                    
                    
                    
        }
        

        
        
    } }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
    
    function physics:get(name)
        return unpack(self.data[name])
    end

    function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
    end
    
    return physics;
end

return M

